config/routes.rb
App::Application.routes.draw do
  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :articles

   root :to => 'categories#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :forums, :dependent => :destroy
  
  # Accessors
  attr_accessible :title, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  # Associations
  has_many :topics, :dependent => :destroy
  has_many :posts, :through => :topics
  
  belongs_to :category
  
  # Accessors
  attr_accessible :title, :description, :state, :position, :category_id
  
  # Scopes
  default_scope :order => 'position ASC'
  
  # Validations
  validates :title,       :presence => true
  validates :description, :presence => true
  validates :category_id, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  # Associations
  belongs_to :forum, :counter_cache => true
  belongs_to :topic, :counter_cache => true, :touch => true 
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessible :body
  
  # Validations
  validates :body, :presence => true
  validates :user, :presence => true
  
  # Default Scope
  default_scope :order => 'created_at ASC'
  
  # Scope to display only the last n posts. Used for "Recent Posts" display
  scope :recent, lambda {
    |c| reorder('created_at desc').limit(c)
  }
  
  # Callbacks
  before_save :topic_locked?
  
  # Methods
  private
    def topic_locked?
      if topic.locked?
        errors.add(:base, "That topic is locked")
        false
      end
    end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  # Associations
  has_many :posts, :dependent => :destroy
  belongs_to :forum, :counter_cache => true
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessor :body
  attr_accessible :title, :body, :sticky, :locked
  
  # Validations
  validates :title,   :presence => true
  validates :body,    :presence => true, :on => :create
  validates :posts,   :presence => true, :allow_nil => false, :on => :update
  validates :user,    :presence => true
  
  # Scopes
  default_scope :order => 'sticky DESC, updated_at DESC'
  
  # Callbacks
  after_create :create_initial_post
  
  # Methods
  def hit!
    self.class.increment_counter :hits, id
  end
  
  private
    def create_initial_post
      self.posts.build(:body => self.body).tap do |post|
        post.forum = self.forum
        post.user = self.user
        post.save
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  validates_presence_of :username

  has_many :topics, :dependent => :destroy
  has_many :posts, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController  
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(params[:category])
    
    if @category.save
      flash[:notice] = "Category was successfully created."
      redirect_to forums_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    
    if @category.update_attributes(params[:category])
      flash[:notice] = "Category was updated successfully."
      redirect_to forums_url
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    
    if @category.destroy
      flash[:notice] = "Category was deleted."
      redirect_to forums_url
    end
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController    
  def show
    @forum = Forum.find(params[:id])
  end
  
  def new
    @forum = Forum.new
  end
  
  def create
    @forum = Forum.new(params[:forum])
    
    if @forum.save
      flash[:notice] = "Forum was successfully created."
      redirect_to forums_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @forum = Forum.find(params[:id])
  end
  
  def update
    @forum = Forum.find(params[:id])
    
    if @forum.update_attributes(params[:forum])
      flash[:notice] = "Forum was updated successfully."
      redirect_to forum_url(@forum)
    end
  end
  
  def destroy
    @forum = Forum.find(params[:id])
    
    if @forum.destroy
      flash[:notice] = "Category was deleted."
      redirect_to forums_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController    
  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    
    if params[:quote]
      quote_post = Post.find(params[:quote])
      if quote_post
        @post.body = quote_post.body
      end
    end
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(params[:post])
    @post.forum = @topic.forum
    @post.user = current_user
    
    if @post.save
      flash[:notice] = "Post was successfully created."
      redirect_to topic_path(@post.topic)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      flash[:notice] = "Post was successfully updated."
      redirect_to topic_path(@post.topic)
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    
    if @post.topic.posts_count > 1
      if @post.destroy
        flash[:notice] = "Post was successfully destroyed."
        redirect_to topic_path(@post.topic)
      end
    else
      if @post.topic.destroy
        flash[:notice] = "Topic was successfully deleted."
        redirect_to forum_path(@post.forum)
      end
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController  
  def show
    @topic = Topic.find(params[:id])
    @topic.hit! if @topic
  end
  
  def new
    @forum = Forum.find(params[:forum_id])
    @topic = Topic.new
  end
  
  def create
    @forum = Forum.find(params[:forum_id])
    @topic = @forum.topics.build(params[:topic])
    @topic.user = current_user
    
    if @topic.save
      flash[:notice] = "Topic was successfully created."
      redirect_to topic_url(@topic)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @topic = Topic.find(params[:id])
  end
  
  def update
    @topic = Topic.find(params[:id])
    
    if @topic.update_attributes(params[:topic])
      flash[:notice] = "Topic was updated successfully."
      redirect_to topic_url(@topic)
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    
    if @topic.destroy
      flash[:notice] = "Topic was deleted successfully."
      redirect_to forum_url(@topic.forum)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/categories/_form.html.erb
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Category</div>
    <div class="module_subheader smaller"></div>
    <div class="module_body">
      <%= form_for @category do |f| %>
      <% if @category.errors.any? %>
        <% flash.now[:error] = @category.errors.full_messages.join(', and ') %>
      <% end %>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :title %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_field :title, :size => 75 %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :position %>
        </span>
        <span class="input indent smaller"><%= f.text_field :position %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller"></span>
        <span class="input indent smaller">
          <%= f.check_box :state %>
          <%= f.label :state %>
        </span>
        <div class="clear"></div>
      </div>
    </div>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit" %> or <%= link_to "cancel", forums_path %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<div class="right controls"><%= link_to "New Forum Category", new_category_path %></div>
<% @categories.each do |category| %>
  <div class="module">
    <div class="module_header">
      <%= category.title %>
      <span class="controls right smaller">
        <%= link_to "New Forum", new_forum_path %>
        <%= link_to "Edit Category", edit_category_path(category) %>
        <%= link_to "Delete Category", category_path(category), :confirm => "Are you sure you want to delete this category?", :method => :delete %>
      </span>
    </div>
    <% if category.forums.size > 0 %>
    <div>
      <table>
        <tr class="smaller">
          <th colspan="2" align="left">Forum</th>
          <th>Topics</th>
          <th>Posts</th>
          <th class="last_post" align="left">Last Post</th>
        </tr>
        <% category.forums.each do |forum| %>
        <tr>
          <td class="icon"><%= image_tag 'ruby.png' %></td>
          <td class="description">
            <%= link_to forum.title, forum_path(forum) %><br />
            <span class="smaller"><%= forum.description %></span><br />
          </td>
          <td class="counts smaller"><%= forum.topics.size %></td>
          <td class="counts smaller"><%= forum.posts.size - forum.topics.size %></td>
          <td class="last_post smaller">
            <% if forum.posts.size > 0 %>
              <%= forum.posts.last.created_at %><br />
              <%= forum.posts.last.user.username %>
            <% else %>
              No Topics / Posts
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <% else %>
      <div class="module_body">There are currently no forums.</div>
    <% end %>
  </div>
<% end %>

app/views/categories/new.html.erb
<%= render :partial => 'form' %>

app/views/forums/_form.html.erb
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Forum</div>
    <div class="module_subheader smaller">
      <em>To create a category, leave the category field unselected.</em>
    </div>
    <div class="module_body">
      <%= form_for @forum do |f| %>
      <% if @forum.errors.any? %>
        <% flash.now[:error] = @forum.errors.full_messages.join(', and ') %>
      <% end %>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :category_id %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller">
          <%= f.collection_select :category_id, Category.all, :id, :title %>
        </span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :title %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_field :title, :size => 75 %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :description %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_area :description, :cols => 60, :rows => 5 %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :position %>
        </span>
        <span class="input indent smaller"><%= f.text_field :position %></span>
        <div class="clear"></div>
      </div>
      <div class="fieldset">
        <span class="label indent smaller"></span>
        <span class="input indent smaller">
          <%= f.check_box :state %>
          <%= f.label :state %>
        </span>
        <div class="clear"></div>
      </div>
    </div>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit" %> or <%= link_to "cancel", @forum.nil? ? forum_path(@forum) : forums_path %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/forums/edit.html.erb
<%= render :partial => 'form' %>

app/views/forums/index.html.erb
<div class="right controls"><%= link_to "New Forum/Category", new_forum_path %></div>
<% @categories.each do |category| %>
  <div class="module">
    <div class="module_header">
      <%= category.title %>
      <span class="controls right smaller">
        <%= link_to "New Forum", new_forum_path %>
        <%= link_to "Edit Category", edit_forum_path(category) %>
        <%= link_to "Delete Category", forum_path(category), :confirm => "Are you sure you want to delete this category?", :method => :delete %>
      </span>
    </div>
    <% if category.forums.size > 0 %>
    <div>
      <table>
        <tr class="smaller">
          <th colspan="2" align="left">Forum</th>
          <th>Topics</th>
          <th>Posts</th>
          <th class="last_post" align="left">Last Post</th>
        </tr>
        <% category.forums.each do |forum| %>
        <tr>
          <td class="icon"><%= image_tag 'ruby.png' %></td>
          <td class="description">
            <%= link_to forum.title, forum_path(forum) %><br />
            <span class="smaller"><%= forum.description %></span><br />
          </td>
          <td class="counts smaller"><%= forum.topics.size %></td>
          <td class="counts smaller"><%= forum.posts.size - forum.topics.size %></td>
          <td class="last_post smaller">
            <% if forum.posts.size > 0 %>
              <%= forum.posts.last.created_at %><br />
              <%= forum.posts.last.user.username %>
            <% else %>
              No Topics / Posts
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <% else %>
      <div class="module_body">There are currently no forums.</div>
    <% end %>
  </div>
<% end %>

app/views/forums/new.html.erb
<%= render :partial => 'form' %>

app/views/forums/show.html.erb
<div class="right controls"><%= link_to "Back to Forum List", forums_path %></div>
<div class="module">
  <div class="module_header">
    <%= @forum.title %>
    <span class="controls right">
      <%= link_to "New Topic", new_forum_topic_path(@forum) %>
      <%= link_to "Edit Forum", edit_forum_path(@forum) %>
      <%= link_to "Delete Forum", forum_path(@forum), :confirm => "Are you sure you want to delete this forum?", :method => :delete %>
    </span>
  </div>
  <div>
    <table>
      <tr class="smaller">
        <th colspan="2" align="left">Topic</th>
        <th>Replies</th>
        <th>Views</th>
        <th class="last_post" align="left">Last Post</th>
      </tr>
      <% @forum.topics.each do |topic| %>
      <tr>
        <td class="icon"><%= image_tag 'ruby.png' %></td>
        <td class="description">
          <%= link_to topic.title, topic_path(topic) %><br />
          <span class="smaller">by <%= topic.user.username %></span>
        </td>
        <td class="counts smaller"><%= topic.posts.size - 1 %></td>
        <td class="counts smaller"><%= topic.hits %></td>
        <td class="last_post smaller">
          <%= topic.posts.last.created_at %><br />
          by <%= topic.posts.last.user.username %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Post</div>
    <div class="module_subheader smaller"></div>
    <div class="module_body">
      <%= form_for [@topic, @post] do |f| %>
      <% if @post.errors.any? %>
        <% flash.now[:error] = @post.errors.full_messages.join(', and ') %>
      <% end %>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :body %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_area :body, :cols => 60, :rows => 15 %></span>
        <div class="clear"></div>
      </div>
    </div>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit" %> or <%= link_to "cancel", @topic %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render :partial => 'form' %>

app/views/posts/new.html.erb
<%= render :partial => 'form' %>

app/views/topics/_form.html.erb
<%= form_for [@forum, @topic] do |f| %>
<% if @topic.errors.any? %>
  <% flash.now[:error] = @topic.errors.full_messages.join(', and ') %>
<% end %>
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Topic</div>
    <div class="module_subheader smaller"></div>
    <div class="module_body">
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :title %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_field :title, :size => 75 %></span>
        <div class="clear"></div>
      </div>
      <% unless @topic.id %>
      <div class="fieldset">
        <span class="label indent smaller">
          <%= f.label :body %><br />
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_area :body, :cols => 60, :rows => 15 %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit" %> or <%= link_to "cancel", @topic.nil? ?  @topic : @forum %></span>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/topics/edit.html.erb
<%= render :partial => 'form' %>

app/views/topics/new.html.erb
<%= render :partial => 'form' %>

app/views/topics/show.html.erb
<div class="right controls"><%= link_to "Back to Forum", forum_path(@topic.forum) %></div>
<div class="module">
  <div class="module_header">
    <%= @topic.title %>
    <span class="right controls">
      <%= link_to "Edit", edit_topic_path(@topic) %>
      <%= link_to "Delete", @topic, :confirm => "Are you sure?", :method => :delete %>
      <%= link_to @topic.sticky ? "Unstick" : "Sticky", {:controller => 'topics', :action => 'update', :topic => {:sticky => @topic.sticky ? "false" : "true" }}, :method => :put %>
      <%= link_to @topic.locked ? "Unlock" : "Lock", {:controller => 'topics', :action => 'update', :topic => {:locked => @topic.locked ? "false" : "true" }}, :method => :put %>
    </span>
  </div>
  <div>
    <table>
      <% @topic.posts.each do |post| %>
      <tr>
        <td class="post_author" rowspan="2">
          <span class="name"><%= post.user.username %></span>
          <span class="avatar"><!-- This space reserved for Avatar --></span>
          <span class="info smaller">
            Posts <%= post.user.posts.size %><br />
            Registered <%= post.user.created_at.to_s(:joined) %><br />
          </span>
        </td>
        <td class="post_header">
          <span class="left post_date smaller">Posted <%= post.created_at %></span>
          <span class="right controls">
            <%= link_to "Reply", new_topic_post_path(@topic) %>
            <%= link_to "Quote", new_topic_post_path(@topic, :quote => post) %>
            <%= link_to "Edit", edit_post_path(post) %>
            <%= link_to "Delete", post, :confirm => "Are you sure?", :method => :delete %>
          </span>
        </td>
      </tr>
      <tr>
        <td class="post_body">
          <%= simple_format(auto_link(post.body)) %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>